language: php

php: ["5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "EMMkPnJdspdHeHgt0Ea6YpNwfXMWz8VYRLQlB+ky5orLjXmNOuBXEvUSxwve2RFb+uoxSOOj35I1g8kD6rCTDmaZH8ePyPctSfIeAM7bymmfwtYv23WxEF7EmTDgZPlki/4W97udoxxTjpXsuOD9BS8hhhjv6eOa7R2txvKtloo="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
