language: php
php:
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- nightly
matrix:
  allow_failures:
  - php: nightly
  fast_finish: true
env:
  global:
  - secure: FIF+gp2tG2b1exzUIhYOtyNJFPl6yCa4PQQf9DQ8QNZmwm9D9lZzupB2Eha1KfTIZFnL1/Xy/Yv18QhnOeAKExEf/d68UBG6Fvu1Mq6Ov3zh59J1LdW7gsep8+XSlbf/7kOiTHjDztSgFBN7wQ1KT08ku04sX8XWm3NAK0/mVM0=
install:
- ./.travis.install
script:
- ./vendor/bin/archer travis:build
